const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'styles', 'admin', 'todo.css');
let content = fs.readFileSync(filePath, 'utf8');

const targetCRLF = '.admin-todo-card-priority {\r\n    flex: 0 0 auto;\r\n\r\n    max-width: 82px;\r\n\r\n    border: 0;\r\n    background: rgba(255, 255, 255, 0.65);\r\n\r\n    border-radius: 999px;\r\n\r\n    padding: 0.18rem 0.4rem;\r\n\r\n    font-size: 0.67rem;\r\n    color: var(--label-color, #5e748d);\r\n    white-space: nowrap;\r\n}';
const targetLF = targetCRLF.replace(/\r\n/g, '\n');

const isCRLF = content.includes(targetCRLF);
const target = isCRLF ? targetCRLF : targetLF;
const eol = isCRLF ? '\r\n' : '\n';

const replacementLines = [
  '.admin-todo-card-priority {',
  '    flex: 0 0 auto;',
  '',
  '    max-width: 82px;',
  '',
  '    border: 0;',
  '    background: rgba(255, 255, 255, 0.65);',
  '',
  '    border-radius: 999px;',
  '',
  '    padding: 0.18rem 0.4rem;',
  '',
  '    font-size: 0.67rem;',
  '    font-weight: 600;',
  '',
  '    color: #1f2d3d;',
  '',
  '    cursor: pointer;',
  '}',
  '',
  '/* ============================================================',
  '   Todo Tabs & Tag Filter Bar',
  '   ============================================================ */',
  '',
  '.admin-todo-nav-bar {',
  '    display: flex;',
  '    flex-direction: column;',
  '    gap: 0.85rem;',
  '    margin-bottom: 1.5rem;',
  '}',
  '',
  '.admin-todo-nav-main {',
  '    display: flex;',
  '    align-items: center;',
  '    justify-content: space-between;',
  '    flex-wrap: wrap;',
  '    gap: 1rem;',
  '    width: 100%;',
  '}',
  '',
  '.admin-todo-nav-bar .admin-tabs {',
  '    margin-bottom: 0;',
  '}',
  '',
  '.admin-todo-search-wrap {',
  '    position: relative;',
  '    display: flex;',
  '    align-items: center;',
  '    width: 100%;',
  '    max-width: 320px;',
  '    min-width: 220px;',
  '}',
  '',
  '.admin-todo-search-icon {',
  '    position: absolute;',
  '    left: 0.75rem;',
  '    color: #94a3b8;',
  '    pointer-events: none;',
  '    display: flex;',
  '    align-items: center;',
  '}',
  '',
  '.admin-todo-search-input {',
  '    width: 100%;',
  '    height: 38px;',
  '    padding: 0 2rem 0 2.25rem;',
  '    font-size: 0.875rem;',
  '    border: 1px solid #dce4ed;',
  '    border-radius: 8px;',
  '    background: #ffffff;',
  '    color: #1e293b;',
  '    outline: none;',
  '    transition: border-color 0.15s ease, box-shadow 0.15s ease;',
  '    font-family: inherit;',
  '    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.02);',
  '}',
  '',
  '.admin-todo-search-input:focus {',
  '    border-color: var(--secondary-color, #4a6b8a);',
  '    box-shadow: 0 0 0 3px rgba(74, 107, 138, 0.14);',
  '}',
  '',
  '.admin-todo-search-input::placeholder {',
  '    color: #94a3b8;',
  '}',
  '',
  '.admin-todo-search-clear {',
  '    position: absolute;',
  '    right: 0.55rem;',
  '    background: transparent;',
  '    border: none;',
  '    color: #94a3b8;',
  '    cursor: pointer;',
  '    font-size: 0.85rem;',
  '    width: 24px;',
  '    height: 24px;',
  '    display: flex;',
  '    align-items: center;',
  '    justify-content: center;',
  '    border-radius: 50%;',
  '    padding: 0;',
  '    line-height: 1;',
  '    transition: color 0.15s ease, background 0.15s ease;',
  '}',
  '',
  '.admin-todo-search-clear:hover {',
  '    color: #1e293b;',
  '    background: rgba(0, 0, 0, 0.06);',
  '}',
  '',
  'body.dark-mode .admin-todo-search-input,',
  '.dark-mode .admin-todo-search-input {',
  '    background: var(--card-bg, #1f2326);',
  '    border-color: rgba(255, 255, 255, 0.12);',
  '    color: #f5f7fa;',
  '}',
  '',
  'body.dark-mode .admin-todo-search-input:focus,',
  '.dark-mode .admin-todo-search-input:focus {',
  '    border-color: #7d9ba6;',
  '    box-shadow: 0 0 0 3px rgba(125, 155, 166, 0.2);',
  '}',
  '',
  'body.dark-mode .admin-todo-search-icon,',
  '.dark-mode .admin-todo-search-icon,',
  'body.dark-mode .admin-todo-search-clear,',
  '.dark-mode .admin-todo-search-clear {',
  '    color: #aab7b8;',
  '}',
  '',
  'body.dark-mode .admin-todo-search-clear:hover,',
  '.dark-mode .admin-todo-search-clear:hover {',
  '    color: #f5f7fa;',
  '    background: rgba(255, 255, 255, 0.1);',
  '}',
  '',
  '@media (max-width: 600px) {',
  '    .admin-todo-nav-main {',
  '        flex-direction: column;',
  '        align-items: stretch;',
  '    }',
  '',
  '    .admin-todo-search-wrap {',
  '        max-width: 100%;',
  '    }',
  '}',
  '',
  '.admin-todo-tag-filter-container {',
  '    display: flex;',
  '    align-items: center;',
  '    gap: 0.5rem;',
  '    flex-wrap: wrap;',
  '}',
  '',
  '.admin-todo-tag-filter-label {',
  '    font-size: 0.8rem;',
  '    font-weight: 600;',
  '    color: var(--label-color, #5e748d);',
  '    white-space: nowrap;',
  '}'
];

const replacement = replacementLines.join(eol);

if (!content.includes(target)) {
  console.error('Target not found in todo.css');
  process.exit(1);
}

content = content.replace(target, replacement);
fs.writeFileSync(filePath, content, 'utf8');
console.log('Successfully updated todo.css!');
